/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
  int a ;
  int b;
    public int soustraction(int a ,int b) {
    	int c = Integer.MAX_VALUE;
    	int d = Integer.MIN_VALUE;
    	
    	return a-b;}
    	 
    public int addition(int a ,int b) {
    	
    	return a+b;
    }
    public int multiplication(int a ,int b) {
    	
    	return a*b;
    	
    }
    public int division(int a ,int b) {
    	
    	return a/b;
    }
}
