/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Assert;
import org.junit.Before;
import org.junit.BeforeClass;

public class LibraryTest2 {
	
	Library Lib;
	
	@BeforeClass
	public static void initdb() 
	{
		System.out.println("DBS sd 5");
	}
	
	@AfterClass
	public static void closedb() {
		System.out.println("DBS finished");
	}
	
	
	@Before
	public void initlibrary() {
	 Lib=new Library();
	 System.out.println("before test");
	}
	
    @Test public void addtest() {
    	
    	System.out.println("test add");
        
        int a =Integer.MAX_VALUE;
        int b=1;
        
        int expectedresult = Integer.MIN_VALUE;;
        
		Lib.addition(a, b);
		
		Assert.assertEquals(expectedresult, Lib.addition(a, b));
        
    }
    
    @Test public void subtest() {
    	
    	System.out.println("test sub");
       
        int a =Integer.MAX_VALUE;
        int b=Integer.MIN_VALUE;
        
        int expectedresult = -1;
        
		Lib.addition(a, b);
		
		Assert.assertEquals(expectedresult, Lib.soustraction(a, b));
        
    }
    @After
	public void finishlib() {
		System.out.println("test finished");
		Lib = null;
	}
    
}
